//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public int Id { get; set; }
        public string KullanıcıAdı { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public bool IsActive { get; set; }
        public bool IsOnline { get; set; }
        public bool IsDelete { get; set; }
        public string Sifre { get; set; }
    }
}
